baseURL = 'http://192.168.1.109:8081/'
languageCode = 'en-us'
title = 'KelsonCraft Blog'
#theme = 'reimu'
theme = 'hello-friend-ng'

# hello-friend-ng params
# logo.html
Params.Logo.logoText = "KCNet Blog"

# header.html
Params.EnableThemeToggle = true
#Params.social = true

#Params.Portrait.Path = "/"

# footer.html
Params.footer.author = true
Params.Author.name = "kelson8"
Params.footer.copyright = true
Copyright = "Copyright 2025 KCNet/KelsonCraft GPLv3"
#Params.footer.rss = true

####
# For 12h hour time.
Params.dateformNumTime = "Jan 2, 2006 at 3:04 PM"

# For 24 hour time.
#Params.dateformNumTime = "2006-01-02 15:04"

#Params.dateformShort = "Jan 2, 2006 at 3:04 PM"

## Test, copied from config.toml in theme

enableRobotsTXT = true
enableGitInfo   = false
enableEmoji     = true


[taxonomies]
  tag = "tags"
  category = "categories"

[params]
  # TODO Figure out how to get the below items to work
  backgroundImage = "assets/images/anime-girl-2880x1800-10025-2754496868.jpg"

  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #  
  # Addon: Social icons
  # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
  #
  [[params.social]]
    name = "twitter"
    url  = "https://twitter.com/"

  [[params.social]]
    name = "email"
    url  = "mailto:nobody@example.com"

  [[params.social]]
    name = "github"
    url  = "https://github.com/"

  [[params.social]]
    name = "linkedin"
    url  = "https://www.linkedin.com/"

  [[params.social]]
    name = "stackoverflow"
    url  = "https://www.stackoverflow.com/"

[menu]
  [[menu.main]]
    identifier = "blog-intro"
    name       = "Blog Intro"
    url        = "posts/blog-intro"
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "posts/"

####